### PR TITLE
Add: wokwi-ci build

### LINKED ISSUE #1: Suggestion: Add wokwi CI testing
src: https://github.com/wokwi/wokwi-ci-action

e.g.:

- https://github.com/georgik/esp32-lang-lab/tree/main/.github/workflows
- https://github.com/kassane/zig-esp-idf-sample/pull/5

cc: @Reavershark

### PR DESCRIPTION
**Pull request by kassane**
Need make account on https://wokwi.com
and add SECRET_KEY

<details>

image
</details>

fix: #1 

doc: https://docs.wokwi.com/wokwi-ci/getting-started#github-actions

**Output:** https://github.com/kassane/esp-dlang/actions/runs/8528765958

**ESP32**
```bash
Wokwi CLI v0.9.1 (cfd2078ca922)
Connected to Wokwi Simulation API 1.0.0-20240319-gc9b55905
Starting simulation...
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1156
load:0x40078000,len:11456
ho 0 tail 12 room 4
load:0x40080400,len:2972
entry 0x400805dc
I (322) cpu_start: Multicore app
I (323) cpu_start: Pro cpu up.
I (323) cpu_start: Starting app cpu, entry point is 0x40080ff0
I (325) cpu_start: App cpu up.
I (341) cpu_start: Pro cpu start user code
I (341) cpu_start: cpu freq: 160000000
I (342) cpu_start: Application information:
I (344) cpu_start: Project name:     example
I (349) cpu_start: App version:      1
I (353) cpu_start: Compile time:     Apr  2 2024 20:13:08
I (359) cpu_start: ELF file SHA256:  76e6ab08587246d3...
I (365) cpu_start: ESP-IDF:          v4.4.7
I (370) cpu_start: Min chip rev:     v0.0
I (375) cpu_start: Max chip rev:     v3.99 
I (380) cpu_start: Chip rev:         v3.0
I (385) heap_init: Initializing. RAM available for dynamic allocation:
I (392) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (398) heap_init: At 3FFB2460 len 0002DBA0 (182 KiB): DRAM
I (404) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (410) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (417) heap_init: At 4008B68C len 00014974 (82 KiB): IRAM
I (424) spi_flash: detected chip: gd
I (427) spi_flash: flash io: dio
I (433) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
Hello, dlang says: i = 0



Expected text found: "Hello, dlang says: i = 0"
TEST PASSED.
```

cc: @Reavershark

### CODE REVIEW

**Comment by kassane** [comment]
Works esp32 only? Already test on any esp32-S device?

**Comment by jnms-me** [comment]
Have some larger changes in the works using importC instead of dpp.
Will look into this once that is pushed.
I only have access to some regular esp32 boards.

**Comment by kassane** [comment]
> I only have access to some regular esp32 boards.

Ok. I'll make some tests using esp32s3 board. However, my local machine has espressif/llvm17.0.1 with ldc1.37.

**Comment by kassane** [comment]
Found the issue on esp32-S(lx7). Actually fixed the `ldc2.conf` setting only for esp32 (lx6).
Would be interesting to make it more dynamic and catch the `$IDF_TARGET`.

**Comment by kassane** [comment]
@Reavershark , finally. Works all targets!!
https://github.com/kassane/esp-dlang/actions/runs/8538939841

**Comment by kassane** [comment]
Do you want to extend support for esp32 riscv? (C2/C3/C5/C6/H2/P4)

In this case, you would need to create new `ldc2.conf` focused on riscv32 targets using `-mcpu=generic-rv32` and `-mattr=`.

C2/C3: `-mattr=+m,+c`
C5/C6/H2: `-mattr=+m,+a,+c`
P4: `-mattr=+m,+a,+c,+f`

Maybe need: `-mabi=ilp32f`/`-mabi=ilp32`

**Comment by jnms-me** [comment]
Merged into branch, will clean up history from there as there's some master commits in the PR (caused by merge instead of rebase).

**Comment by kassane** [comment]
> Do you want to extend support for esp32 riscv? (C2/C3/C5/C6/H2/P4)
> 
> In this case, you would need to create new `ldc2.conf` focused on riscv32 targets using `-mcpu=generic-rv32` and `-mattr=`.
> 
> C2/C3: `-mattr=+m,+c` C5/C6/H2: `-mattr=+m,+a,+c` P4: `-mattr=+m,+a,+c,+f`
> 
> Maybe need: `-mabi=ilp32f`/`-mabi=ilp32`

@Reavershark 
see https://github.com/kassane/esp-dlang/compare/Reavershark%3Aesp-dlang%3Amaster...tests
https://github.com/kassane/esp-dlang/actions/runs/8666963160  - run all esp32 devices... missing c5 and p4.

but P4 is unstable yet... https://github.com/wokwi/wokwi-features/issues/758#issuecomment-2019426726

**Pull request merged**
